version: '2'
services:
  splunk:
    image: dmaxwell/splunk
    container_name: splunk
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
    links:
        - syslog:syslog 
  syslog:
    image: voxxit/rsyslog



#
#1. splunk enable app SplunkForwarder -auth <username>:<password>
#2. add the following config to /opt/splunk/etc/apps/SplunkForwarder/default/outputs.conf
#
#[syslog]
#defaultGroup=syslogGroup

#[syslog:syslogGroup]
#server = syslog:514
