version: "2"

services:
  elasticsearch:
    image: elasticsearch:2.4.0
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    build: ./
    ports:
      - "5601:5601"
        #environment:
        # ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    external: true
